import { StyleSheet } from 'react-native';
import { responsiveFontSize, responsiveHeight, responsiveWidth } from 'react-native-responsive-dimensions';

const HomeStyles = StyleSheet.create({
    Main: {
        paddingHorizontal: responsiveWidth(4),
        flex: 1,
    },
    ScrollContainer: {
        flexGrow: 1,
        paddingHorizontal: 10,
        // paddingBottom: 100,
    },
    img: {
        height: 50,
        width: 50,
        borderRadius: 9999,
        // backgroundColor: 'white',
        justifyContent: 'center',
        alignItems: 'center',
        // borderColor: 'white',
        borderWidth: 0.5,
    },
    initials: {
        fontSize: responsiveFontSize(3),
        fontWeight: 'bold',
        color: '#000',
        textAlign: 'center',
        // fontSize: 20,
        // fontWeight: 'bold',
        // color: '#000',
        // textAlign: 'center',
        lineHeight: 50,
    },
    FirstCont: {
        backgroundColor: '#87CEFA',
        borderRadius: 9,
        marginVertical: responsiveHeight(3),
        paddingHorizontal: responsiveWidth(4),
        paddingVertical: responsiveHeight(2),
        display: 'flex',
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    txt: {
        fontSize: responsiveFontSize(2.5),
        color: '#1E2C34',
        fontWeight: '700',
    },
    dateCont: {
        backgroundColor: '#1E2C34',
        borderRadius: 9,
        paddingHorizontal: responsiveWidth(1),
        paddingVertical: responsiveHeight(0.5),
        display: 'flex',
        flexDirection: 'column',
        justifyContent: 'center',
        alignItems: 'center',
        width: responsiveWidth(10),
    },
    dateText: { fontSize: responsiveFontSize(2.2), color: 'white', fontWeight: '400' },
    dayText: { fontSize: responsiveFontSize(1), color: 'white', fontWeight: '700' },
    Text: { fontSize: responsiveFontSize(1.5), color: 'white', fontWeight: '500' },
    divider: {
        marginHorizontal: 10,
        borderColor: '#1E2C34',
        borderWidth: 2,
        width: responsiveWidth(5),
    },

    contTwoBox: {
        borderRadius: 9,
        paddingHorizontal: responsiveWidth(1),
        paddingVertical: responsiveHeight(0.5),
        display: 'flex',
        flexDirection: 'column',
        justifyContent: 'center',
        alignItems: 'center',
        width: '32%',
        height: '70%',
    },
    contnext: {
        borderRadius: 9,
        paddingHorizontal: responsiveWidth(0.8),
        paddingVertical: responsiveHeight(0.5),
        display: 'flex',
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        width: '30%',
        height: '70%',
    },

    journalCont: {
        display: 'flex',
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        width: '100%',
    },

    contentContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        paddingHorizontal: responsiveWidth(1),
    },

    normalText: {
        fontSize: responsiveFontSize(1.8),
        fontWeight: '500',
        textAlign: 'center',
    },

    journalText: {
        fontSize: responsiveFontSize(1.8),
        fontWeight: '500',
        textAlign: 'center',
        width: '100%',
        color: '#00000059',
        paddingHorizontal: responsiveWidth(0.1),
    },

    btn: {
        padding: 10,
        borderRadius: 10,
        marginHorizontal: 5,
        width: '45%',
    },
    btn2: {
        padding: 10,
        borderRadius: 10,
        marginHorizontal: 5,
        width: '30%',
    },
    modal: {
        backgroundColor: '#0A2F36',
        padding: 20,
        borderRadius: 47,
        width: responsiveWidth(95),
        height: responsiveHeight(80),
    },
    contt: {
        display: 'flex',
        flexDirection: 'column',
        justifyContent: 'center',
        marginVertical: responsiveHeight(1),
        alignItems: 'center',
    },
    cont2: {
        display: 'flex',
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        gap: 10,
        marginTop: responsiveHeight(1),
    },
    modaltxt: {
        fontSize: responsiveFontSize(2.5),
        color: '#FFFFFF',
        fontWeight: '600',
        textAlign: 'center',
        marginTop: responsiveHeight(1),
    },
    modaltext: {
        fontSize: responsiveFontSize(2.5),
        color: '#FFFFFF',
        fontWeight: '600',
        textAlign: 'left',
    },
    smtext: {
        fontSize: responsiveFontSize(1.5),
        color: '#FFFFFF',
        fontWeight: '600',
        textAlign: 'left',
        marginTop: responsiveHeight(1.5),
    },
    buttonOne: {
        height: responsiveHeight(5),
        justifyContent: 'center',
        borderRadius: 12,
        width: responsiveWidth(60),
        paddingLeft: responsiveWidth(2),
    },
    button: {
        height: responsiveHeight(5),
        justifyContent: 'center',
        borderRadius: 12,
    },
    emptyContainer: {
        alignItems: 'center',
        justifyContent: 'center',
    },

    subText: {
        fontSize: responsiveFontSize(1),
        color: 'black',
        marginTop: 2,
        textAlign: 'center',
    },
    Happiest: {
        color: 'white',
        fontSize: responsiveFontSize(2.5),
        fontWeight: '600',
    },
    day: {
        color: '#01F0D9',
        fontSize: responsiveFontSize(2.5),
        fontWeight: 'bold',
        marginVertical: responsiveHeight(3),
    },
    emergencyButtonStyle: {
        backgroundColor: '#3E5659',
        height: responsiveWidth(14),
        borderRadius: 30,
        justifyContent: 'center',
        alignItems: 'center',
        marginTop: responsiveHeight(1.5),
        marginBottom: responsiveHeight(1.7),
    },
});
export default HomeStyles;
