import { StyleSheet } from 'react-native';
import { responsiveFontSize, responsiveHeight, responsiveWidth } from 'react-native-responsive-dimensions';

const ProfileStyles = StyleSheet.create({
    Main: {
        paddingHorizontal: responsiveWidth(4),
        flex: 1,
    },
    ScrollContainer: {
        flexGrow: 1,
        paddingHorizontal: responsiveWidth(2),
        marginBottom: responsiveHeight(4),
    },
    btn: {
        display: 'flex',
        flexDirection: 'row',
        justifyContent: 'space-between',
        borderColor: '#0A2F36',
        borderWidth: 1,
        borderRadius: 12,
        alignItems: 'center',
        paddingHorizontal: responsiveWidth(4),
        height: responsiveHeight(7),
        marginVertical: responsiveHeight(1),
    },
    lastBtn: {
        backgroundColor: '#1AC398',
    },
    other: {
        display: 'flex',
        flexDirection: 'row',
        justifyContent: 'space-between',
        borderColor: '#1AC398',
        borderWidth: 1,
        borderRadius: 12,
        alignItems: 'center',
        paddingHorizontal: responsiveWidth(4),
        height: responsiveHeight(7),
        marginVertical: responsiveHeight(1),
    },
    otherlast: {
        borderColor: '#22BCD4',
        borderWidth: 1,
        borderRadius: 12,
    },
    heading: {
        fontSize: responsiveFontSize(2),
        fontWeight: '700',
        color: '#CCCCCC',
    },
    Name: {
        fontWeight: '700',
        color: 'white',
        marginTop: responsiveHeight(2),
    },
    Email: {
        color: '#9CA3AF',
        fontWeight: '500',
    },
    img: {
        height: 100,
        width: 100,
        borderRadius: 9999,
        backgroundColor: 'white',
        alignItems: 'center',
        justifyContent: 'center',
        opacity: 0.8,
    },
    imgContainer: {
        width: 100,
        height: 100,
        borderRadius: 9999,
        backgroundColor: 'white',
        justifyContent: 'center',
        alignItems: 'center',
        marginTop: responsiveHeight(3),
    },
    modalBackground: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: 'rgba(0, 0, 0, 0.5)',
    },
    modalContainer: {
        padding: 20,
        borderRadius: 12,
        width: responsiveWidth(70),
        // alignItems: "center",
    },
    modalTitle: {
        fontSize: responsiveFontSize(1.8),
        color: '#0A2F36',
        fontWeight: '600',
        textAlign: 'center',
    },
    modalContent: {
        fontSize: responsiveFontSize(1.7),
        color: '#0A2F36',
        fontWeight: '400',
        textAlign: 'center',
        marginBottom: responsiveHeight(3),
    },
    close: {
        display: 'flex',
        justifyContent: 'flex-end',
        flexDirection: 'row',
        alignContent: 'flex-end',
    },
    initials: {
        fontSize: responsiveFontSize(6),
        fontWeight: 'bold',
        color: '#000',
        textAlign: 'center',
        lineHeight: 40,
        marginBottom: 15,
    },
    editIconContainer: {
        position: 'absolute',
        top: '50%',
        left: '45%',
        transform: [{ translateX: -15 }, { translateY: -15 }],
        borderRadius: 9999,
        width: 40,
        height: 20,
        alignItems: 'center',
        justifyContent: 'center',
        zIndex: 10,
    },
});
export default ProfileStyles;
